services:
  structaddress:
    image: structaddress
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    environment:
      - GROQ_API_KEY=$GROQ_API_KEY
